---
- hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Login to default registry in Azure
    containers.podman.podman_login:
      username: acrpracticados
      password: ktvr7ROAEZHzduBgCj3HnFmCGYdkR9zLFsdtBCfCnF+ACRBz94OA
      registry: acrpracticados.azurecr.io
  - name: Pull image webserver:v1.0 to vm1
    containers.podman.podman_image:
      name: acrpracticados.azurecr.io/webserver:v1.0
  - name: Run container webserver:v1.0 in vm1
    containers.podman.podman_container:
      name: mywebserver
      image: acrpracticados.azurecr.io/webserver:v1.0
      state: started
      detach: true
      ports:
        - 443:443
  